

  INSERT INTO EMPLOYEE (FIRSTNAME, LASTNAME, ID) VALUES ('John', 'Smith', 'X00000');

  UPDATE EMPLOYEE SET IS_ACTIVE=TRUE WHERE ID='X00000';

  INSERT INTO EMPLOYEE (FIRSTNAME, LASTNAME, ID) VALUES ('Ashok', 'Kumar', 'X00001');

   UPDATE EMPLOYEE SET IS_ACTIVE=TRUE WHERE ID='X00001';